### ISSUE TITLE
Correct Chart of Accounts

### ISSUE THREAD

**Issue by o-psi** [twetech/itflow#3]

**Comment by o-psi** [comment]
@elizabethcarvajal What do you notice as incorrect other than incomplete information?

**Comment by elizabethcarvajal** [comment]
Delete "Bank - Broadway Bank" account.
Delete "Direct Deposit" from "Payroll" description.
Add "Contract Labor" account.
Delete "Sales Tax - Federal Taxes" account.
Delete "Sales Tax - State Comptroller" account.

________________________________

**Comment by o-psi** [comment]
This has been done.
